### PR TITLE
Work with (only) aeson 2.

### PR DESCRIPTION
**Pull request by athas**
The actual Haskell-level code changes are simple enough, but I got stuck on adding overrides with never package versions for the Nix build because ormolu is packaged weirdly.

### CODE REVIEW

**Comment by athas** [comment]
`pkgs.ormolu` doesn't work with path-0.9.2, which is transitivitely needed by other dependencies (ultimately it's all so all the dependencies will work with aeson-2).  The newest version (`pkgs.ormolu_0_4_0_0`) requires GHC 9.2, while Nixpkgs still uses GHC 8.10.7.  It's a bit frustrating because ormolu isn't a Haskell-level dependency of Nix, but used for some of the other stuff going on in default.nix (which I don't fully understand).  I see two options:

1. Switch over to the GHC 9.2 package set.
2. Don't use pkgs.ormolu in default.nix, but instead some `origPkgs` package set that doesn't include the overrides of haskellPackages that we need for Niv.  I do something similar in my own Haskell projects, but my Nix setup is much simpler, and I don't really understand why the ormolu stuff is in default.nix in the first place (I usually put that in shell.nix).

I think option 2 is more attractive, because it cleanly separates overrides needed for Niv's Haskell dependencies itself from tool dependencies that just happen, as an implementation detail, to be written in Haskell.  I don't think Niv should care about ormolu's dependencies.

**Comment by athas** [comment]
I figured it out.  It should work now.

**Comment by athas** [comment]
Could you approve the GA workflow please?

**Comment by athas** [comment]
I had add a new version of the shell.nix file due to the formatting fixes.  (I guess?  It's a bit unclear to me what this is doing.)  And now it looks like you have to approve the workflow again.

**Comment by athas** [comment]
Alright, the tests pass locally now.  I *think* this is the last time you'll have to approve this workflow.

**Comment by athas** [comment]
Rebased on top of master.

**Comment by athas** [comment]
(And I personally want to use the `haskell-updates` branch for my project, which currently has a broken `niv`.)

**Review by nmattia — APPROVED** [review]
Sorry for dropping the ball on this! I don't think there's anything missing although I'm still confused as to why we need to specify those cabal dependency versions explicitly. But if this fixes things, happy to merge!

**Comment by athas** [comment]
I assume you mean the versions in default.nix?  That's because the default packages in the Haskell package set in Nixpkgs is held back on older versions that do not support aeson-2, but in those cases also contain a the newest version of the corresponding package.  The reason is that some dependent packages judged important (like Niv itself I guess) don't support aeson-2.  *Ultimately* the reason is that Nixpkgs tries to be a consistent package set such that all Haskell derivations use the same version of all dependencies, which is a frightful mess when foundational packages such as aeson have compatibility breaks.  But it's something that'll get better, not worse, with time.  At least until aeson-3...

**Comment by nmattia** [comment]
Gotcha, I think I'm finally understanding what this is about. I've also just noticed that nixpkgs master still has aeson `1.X` whereas the latest released aeson version is `2.X`. With all that in mind, I think it's probably best to stick to nixpkgs master in this repo; as far as I understand this won't be an issue. I think the best way to go forward is to add some CPP directives so that niv can use both versions of aeson; that way we can still use vanilla nixpkgs master here, but you'll be able to use niv with aeson v2. WDYT? Sorry for the back and forth, though I'll admit the intent of the PR wasn't really clear :)

**Comment by athas** [comment]
Nixpkgs master also has aeson-2, just under a different name.  There are packages that use it, and presumably so would an aeson-2 dependent version of Niv (I think; I don't understand all the automation around the Haskell part of Nixpkgs).  This PR *does* still use Nixpkgs master, just a newer commit.  There is nothing here that uses anything not part of Nixpkgs.

Using CPP in Niv is possible, but I don't like doing that kind of programming myself.  If that's your preferred approach, I'll close this PR so someone else can have a go at it.

**Comment by nmattia** [comment]
Thanks a lot!

**Comment by athas** [comment]
Great, thanks!  I suggest making a release on Hackage soon.

**Comment by nmattia** [comment]
There you go: https://hackage.haskell.org/package/niv-0.2.20

Thanks for the port to aeson 2!

**Pull request merged**
