### PR TITLE
GITHUB_TOKEN env variable support for github fetcher

### PR DESCRIPTION
**Pull request by kubek2k**
it fixes the issue with rate limiting in certain environments (like ZuriHac ;) )

### CODE REVIEW

**Comment by michaelpj** [comment]
Legit compile error.

**Comment by domenkozar** [comment]
Nice! It would be a tiny bit better to use netrc for convenience.

**Comment by kubek2k** [comment]
@domenkozar I think this is an intermediate step towards use of `fetchFromGithub` anyway.

**Comment by nmattia** [comment]
Unfortunately I doubt it'll help: https://github.com/nmattia/niv/issues/62#issuecomment-501747871

**Pull request merged**
