### PR TITLE
ci: add nixpkgs-fmt check (v2)

### PR DESCRIPTION
**Pull request by zimbatm**

### CODE REVIEW

**Comment by nmattia** [comment]
Seems to work!

**Comment by zimbatm** [comment]
Just a heads-up: nixpkgs-fmt is recompiled from source everytime and the CI now takes 6m 45s

**Comment by zimbatm** [comment]
fixed PR

**Comment by nmattia** [comment]
Done! Should land in nixpkgs soon-ish.

**Pull request merged**
