### PR TITLE
Introduce `add` subcommand per fetcher type

### PR DESCRIPTION
**Pull request by nlewo**
This commit introduces subcommand to the `add` command. These
subcommands permit to specify a fetcher type in order to be able to
specify options per fetcher type. For instance, the `--branch` option is
useless for the `file` fetcher. Thanks to this commit, the `--branch`
option is only displayed in the help of the `niv add github` command.

Some usage examples:

    niv add github stedolan/jq
    niv add github NixOS/nixpkgs-channels -n nixpkgs -b nixos-18.09

    niv add file my-package -v alpha-0.1 -t http://example.com/archive/<version>.zip

TODO:
- [x] Update readme

### CODE REVIEW

**Comment by nmattia** [comment]
Nice, thanks! Why not have a flag instead? e.g.

``` shell
$ niv add --github ...
$ niv add --docker ...
```

I understand that in that case the help message may become a bit long but at least you can still write

``` shell
$ niv add nmattia/niv
```
which I think is invaluable. Or maybe we can have an optional subcommand? is that possible with optparse?

**Comment by nlewo** [comment]
I dont' think we could have a nice help menu with flags since they are not really suitable to group arguments.

What about trying to create a special `add` subcommand that could be used as a shortcut:
    
    $ niv add github ...
    $ niv add nmattia/niv ...

However, I don't know if it is possible with the lib :/

**Comment by nmattia** [comment]
I gave this a try, I think there are a few solutions: https://github.com/nmattia/niv/commit/bdd3e98bb8500810d5fdb7062e025233517dd80a

Let's pair and see what we can come up with!

**Comment by nmattia** [comment]
Closing, handled in #151

**Pull request closed without merging**
