### PR TITLE
Enable building with latest nixpkgs

### LINKED ISSUE #297: niv doesn't build with latest nixpkgs
I'm trying out niv for my repo and when I try to use nix version from `sources.nix` created by `niv init`, I'm getting following build failure:
```hs
src/Niv/Update.hs:299:3: error: [-Woverlapping-patterns, -Werror=overlapping-patterns]
    Pattern match is redundant
    In a case alternative: _ -> ...
    |
299 |   _ -> Just $ pure T.empty
    |   ^^^^^^^^^^^^^^^^^^^^^^^^
```

Steps to reproduce:
* in empty dir, run `niv init`
* change `nix/sources.json` to match:
```json
{
    "niv": {
        "branch": "master",
        "description": "Easy dependency management for Nix projects",
        "homepage": "https://github.com/nmattia/niv",
        "owner": "nmattia",
        "repo": "niv",
        "rev": "ba57d5a29b4e0f2085917010380ef3ddc3cf380f",
        "sha256": "1kpsvc53x821cmjg1khvp1nz7906gczq8mp83664cr15h94sh8i4",
        "type": "tarball",
        "url": "https://github.com/nmattia/niv/archive/ba57d5a29b4e0f2085917010380ef3ddc3cf380f.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    },
    "nixpkgs": {
        "branch": "master",
        "description": "Nix Packages collection",
        "homepage": "",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "272744825d28f9cea96fe77fe685c8ba2af8eb12",
        "sha256": "0sn0bcdlp8zm1jca73wcvm7p6miq6gp81kjkcl7b9gbwzcnxac7l",
        "type": "tarball",
        "url": "https://github.com/NixOS/nixpkgs/archive/272744825d28f9cea96fe77fe685c8ba2af8eb12.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    }
}
```
* add `test.nix` with following contents:
```nix
let
  sources = import ./nix/sources.nix;
  pkgs = import sources.nixpkgs {};
  niv = import sources.niv { inherit pkgs; };
in
  niv.niv
```
* run `nix-build test.nix`

Note that `pkgs.niv` works fine, even though it's built with the same compiler and the line in question is present in 0.2.18 tag used there.

### PR DESCRIPTION
**Pull request by lrworth**
[The latest nixpkgs sets GHC 8.10 as default](https://discourse.nixos.org/t/new-ghc-default-version-8-10-2-package-versions-now-from-stackage-nightly/10117), and this version of GHC won't compile Niv due to stricter defaults. This PR bumps nixpkgs to latest master and fixes that compile error.

There were a few other things which needed to be fixed before I could do this:
* nixpkgs-fmt needed latest nixpkgs master in order to build on macOS Big Sur; I have submitted [a PR upstream](https://github.com/nix-community/nixpkgs-fmt/pull/224).
* Because nixpkgs-fmt was updated, the formatting of all .nix files changed slightly, meaning there needed to be a new listed version of sources.nix (V25).
* Latest ormolu formats Haskell sources slightly differently.
* Running `./script/gen` formatted README.md slightly differently.
* The cpp-libosmium example needed latest nixpkgs master in order to build on macOS Big Sur.

Resolves #297

### CODE REVIEW

**Comment by lrworth** [comment]
nixpkgs-fmt needs to be pointed at the nix-community/nixpkgs-fmt repo before this can be merged.

**Review by nmattia — COMMENTED** [review]
Hi, thanks a lot for doing this! A few questions:

* There are some (non-aesthetic) changes in sources.nix, is it possible you were using an older version?
* Do you reckon we'll be able to pin nixpkgs 20.09 or do we need master?

Happy to merge as soon as that's clarified.

**Comment by lrworth** [comment]
I believe sources.nix was changed automatically by `./script/gen`, but I'll run the process again to check. (Granted, I also could've done a better job at organising the commits.)

My initial motivation for this change was to get a project building on macOS Big Sur, which is not supported by nixpkgs 20.09, but is supported in the latest nixpkgs master; so I don't think we can pin 20.09 if we want to support the latest macOS.

**Comment by lrworth** [comment]
I've redone this change based on the latest version of `niv`, and pinned to `nixpkgs-unstable` instead of `master` to get better caching.

**Comment by lrworth** [comment]
CI is failing for configuration reasons, not because this PR is broken

**Review by nmattia — COMMENTED** [review]
Hey man,

Thanks a lot for this! I was completely snowed under the past few weeks, didn't mean to drop the ball.

This looks very good overall. Any chance we can get this to work with 20.09? Or maybe we should wait for 21.03?

**Comment by lrworth** [comment]
No worries @nmattia!

Release 20.09 is unable to complete the linking phase for any package on macOS Big Sur, that's why this PR exists at all. I reckon delay this until 21.03 if you'd prefer to stay on nixpkgs releases.

**Comment by lrworth** [comment]
https://github.com/NixOS/nixpkgs/pull/105799 will make 20.09 work with Big Sur.

**Comment by nmattia** [comment]
Great, looks like there's still some activity on https://github.com/NixOS/nixpkgs/pull/105799, let's wait for that to go in if you don't mind! I'll check back here next week.

**Comment by nmattia** [comment]
@lrworth looks like https://github.com/NixOS/nixpkgs/pull/105799 was merged, should we give this another try?

**Comment by SuperSandro2000** [comment]
> @lrworth looks like [NixOS/nixpkgs#105799](https://github.com/NixOS/nixpkgs/pull/105799) was merged, should we give this another try?

It wasn't merged. It was closed because it does not work.

**Comment by nmattia** [comment]
Ah man got too used to bors closing PRs instead of merging them. My bad.

**Comment by refnil** [comment]
Am I correct in saying that PR was essentially merged under [this commit](https://github.com/nmattia/niv/commit/94080ae8286024820c570a2a24ed7c36d7ad04a9) by @nmattia ?
If so, we could close this PR.

**Comment by lrworth** [comment]
Looks like it 🎈

**Pull request closed without merging**
