### PR TITLE
init at 19.09

### PR DESCRIPTION
**Pull request by kampka**
I think 19.09 is stable enough to be the new default by now :)

### CODE REVIEW

**Comment by nmattia** [comment]
Makes sense! I'm guessing you `grep`ed for `03` throughout the codebase?

**Comment by kampka** [comment]
I sed-ed `19.03` to `19.09`

**Comment by nmattia** [comment]
I ran `niv update nixpkgs` to point to 19.09, looks like there's some issues with CA certs. I'll try to have a look this week!

**Comment by kampka** [comment]
Turns out the generic builder touches the`*SSL_CERT_FILE` variables in shells, setting them to invalid values at https://github.com/nixos/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L634
Unsetting these explicit mis-directions fixes it for me.

**Comment by nmattia** [comment]
Well that's annoying! Thanks for debugging this :)

**Comment by nmattia** [comment]
I'll cut a release tonight!

**Comment by kampka** [comment]
Thanks for taking the time :)

**Comment by flokli** [comment]
This will trickle into nixpkgs via the hackage bumps, or is there a better way to get it? I assume people on NixOS 19.09 might want to use it, too…

**Comment by nmattia** [comment]
@flokli you can alway `niv update niv` or `nix-env -iA niv ...` (see README). For this landing in nixpkgs... yeah, the hackage magic has to kick in.

**Comment by flokli** [comment]
yeah sure, I'm more talking about the bootstrapping problem.

It'd be nice to be able to invoke `niv init` on a NixOS 19.09 and get it `nixpkgs` pointed to 19.09 there.

I doubt hackage magic happens for anything than nixpkgs master :-/

**Pull request merged**
