### PR TITLE
Add ormolu to dev environment

### LINKED ISSUE #221: Set up ormolu
https://github.com/tweag/ormolu

### PR DESCRIPTION
**Pull request by bsima**
Closes #221

### CODE REVIEW

**Comment by nmattia** [comment]
Nice! how does one use this?


Sorry for the delay, I was out for a while!

**Comment by bsima** [comment]
It will be in your nix-shell environment, from vim you can `:!ormolu -m inplace %` and from emacs I think it's `M-! ormolu RET` or use this package: [ormolu.el](https://github.com/vyorkin/ormolu.el)

I didn't actually run ormolu on any of the source because I didn't want to reformat everything and have a huge diff that could cause conflicts. Ofc I could do that, or maybe put a CI check that does `ormolu --mode check $changed_file` to encourage new commits to have formatted code. In either case, at least the tooling is ready for it.

**Comment by nmattia** [comment]
>  maybe put a CI check that does ormolu --mode check $changed_file to encourage new commits to have formatted code

Yes, that would be great! It'd be ideal to also have a simple executable (script, like `niv-fmt`) that formats the source code. I finally get to use Ormolu! :tada:

**Comment by nmattia** [comment]
Thanks @bsima ! I've simplified a bit, in particular I'm now just using Ormolu from nixpkgs.

**Comment by bsima** [comment]
Ah just saw this, thanks for taking it to the finish line! I had to de-prioritize it on my todo list because of other work.

**Pull request merged**
