### PR TITLE
Add fetcher types for builtin tarball and fetchurl fetchers

### PR DESCRIPTION
**Pull request by michaelpj**
I whipped up a possible solution to https://github.com/nmattia/niv/issues/46. Much bikeshedding on the exact form is possible!

One quirk: I've written an auto-calling function here, which I think will ease the process of passing arguments through as we add more fetchers. It means we can answer the question of "what arguments get passed to the fetcher" as "everything that's in your spec that's a valid argument". So it's easy to add e.g. `fetchSubmodules` if you want that when we have `fetchgit`.

I also made `builtin-tarball` the default, since AFAICT it has no real disadvantages, and doens't require nixpkgs.

### CODE REVIEW

**Comment by michaelpj** [comment]
Is it just me or does the svg include adding niv, and hence presumably it will change every time anyone commits to this repo (since it includes the hash as part of the download notification)? That seems a bit eager...

**Comment by nmattia** [comment]
Yeah the svg stuff is a bit picky and not ideal... don't worry about it, I'll push the update.

I'm struggling to understand https://github.com/nmattia/niv/issues/46#issuecomment-495310266: what exactly do you mean by the following?

> [it] means that when I fetch X I need to do it with a builtin fetcher unless I want to fallback on the ambient nixpkgs

**Comment by michaelpj** [comment]
Imagine I have a repository X which defines an expression that looks like this:
```
{
    pinnedNixpkgs = ...
    ...
}
```
that is, it defines a pinned copy of nixpkgs as well as some other things. One reason you might want to do this is where X is something like "company common nix expressions", and you want to select the nixpkgs pin that people use centrally (maybe you're using a fork of nixpkgs!).

We also need another piece: some of us care about having our builds be as absolutely reproducible as possible. That means not relying on the host `NIX_PATH` for anything, even fetchers. Admittedly, it's hard to see what could go wrong with people using different versions of fetchers, but it's nice to be able to make the absolute statement that you don't depend on `NIX_PATH` and so you never need to worry about it.

Putting these two together, I want to fetch X, but I don't want to use a fetcher from a host nixpkgs. That's okay, I can use the builtin fetchers... so long as `niv` gives me a way to do that.

(In an ideal world I'd then be able to somehow indicate that I want to use `X.pinnedNixpkgs` to get any nixpkgs fetchers for other niv dependencies, but I can live without that. For my purposes I'd probably fetch *everything* with the builtin fetchers.)

**Comment by michaelpj** [comment]
Gentle prod. The ability to use builtin fetchers is the only thing preventing me from using this at work!

**Comment by nmattia** [comment]
Hey @michaelpj ,

I just came back from holidays, sorry about the delay :) I'll push a commit with the SVG update and merge. Thanks for the contribution!

**Comment by michaelpj** [comment]
Thanks! Please do feel free to tweak how it works or the names, I'm not attached to the details!

**Comment by nmattia** [comment]
Okay, updated the svg and wrapped my head around the rationale and implementation. AFAICT @nlewo this won't break the hydra use case. Waiting for CI and we're good to go!

**Pull request merged**
